version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    expose:
      - "3001:80"
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    stdin_open: true
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase?schema=public
      - PORT=3000
      - JWT_SECRET=123
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    links:
      - backend

volumes:
  pgdata:
